site_name: "HQME"

# mkdocs.yml
theme:
  name: "material"
  locale: en
  highlightjs: true
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - User Guide: 
      overview: '/user-guide/overview'
  - Developer Guide:
      overview: '/developer-guide/overview'
  - API Reference: API.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - admonition
  - pymdownx.betterem:
      smart_enable: all

plugins:
  - search
  - mkdocstrings